# Setup
title:        Mitradip Das
tagline:      Welcome to my personal homepage
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Mitradip Das
  url:        http://mitradip.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown 